AllCops:
  Exclude:
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'bin/*'
    - 'lib/tasks/*'

Bundler/OrderedGems:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 20

Metrics/LineLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9

Metrics/AbcSize:
  Max: 20
